# coding: utf-8

"""
    Arithmetic Operations API

    API for performing basic arithmetic operations

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from calcssdkpython.api.arithmetic_operations_api import ArithmeticOperationsApi


class TestArithmeticOperationsApi(unittest.TestCase):
    """ArithmeticOperationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ArithmeticOperationsApi()

    def tearDown(self) -> None:
        pass

    def test_divide_post(self) -> None:
        """Test case for divide_post

        Divide a list of numbers
        """
        pass

    def test_multiply_post(self) -> None:
        """Test case for multiply_post

        Multiply a list of numbers
        """
        pass

    def test_subtract_post(self) -> None:
        """Test case for subtract_post

        Subtract a list of numbers
        """
        pass

    def test_sum_post(self) -> None:
        """Test case for sum_post

        Sum a list of numbers
        """
        pass


if __name__ == '__main__':
    unittest.main()
