# coding: utf-8

"""
    Arithmetic Operations API

    API for performing basic arithmetic operations

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from calcssdkpython.models.sum_response import SumResponse

class TestSumResponse(unittest.TestCase):
    """SumResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SumResponse:
        """Test SumResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SumResponse`
        """
        model = SumResponse()
        if include_optional:
            return SumResponse(
                sum = 1.337
            )
        else:
            return SumResponse(
        )
        """

    def testSumResponse(self):
        """Test SumResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
